# -*- mode: ruby -*-
# vi: set ft=ruby :
require './config'

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["./vagrant","~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "./vagrant.pub", destination: "~/.ssh/authorized_keys"
  config.vm.network "private_network", type: "dhcp"
  
  config.vm.provision "shell" do |s|
    s.path = "./prepare.sh"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = "1024"
    vb.name = "#{APP_NAME}"
  end

  config.vm.synced_folder APP_HOME, "/opt/#{APP_NAME}"
end
